name: Aktualizacja RSS

on:
  schedule:
    - cron: '0 * * * *' # co godzinę
  workflow_dispatch:

jobs:
  update-rss:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script
      run: python trojmiasto_rss.py

    - name: Commit and push if changed
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "GitHub Actions Bot"
        git config user.email "bot@github.com"
        git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
        git add trojmiasto_rss.xml debug_trojmiasto.html || true
        git commit -m "Automatyczna aktualizacja RSS $(date)" || echo "Brak zmian"
        git push || echo "Brak uprawnień do pushowania"