name: RSS Update Workflow

on:
  push:
    branches:
      - main

jobs:
  update-rss:
    runs-on: ubuntu-24.04

    steps:
      # Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Upewnij się, że używasz wersji, którą chcesz

      # Install dependencies
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # Run the update script
      - name: Run update script
        run: python trojmiasto_rss.py