name: Aktualizacja RSS

on:
  schedule:
    - cron: '0 * * * *'  # Co godzinę
  workflow_dispatch:     # Możliwość ręcznego odpalenia

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.PAT_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.1

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run RSS generator
        run: python trojmiasto_rss.py

      - name: Commit RSS file
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "bot@github.com"
          git remote set-url origin https://x-access-token:${TOKEN}@github.com/${{ github.repository }}
          git add trojmiasto_rss.xml debug_trojmiasto.html
          git commit -m "Automatyczna aktualizacja RSS $(date)" || echo "Brak zmian"
          git push