name: Update RSS

on:
  schedule:
    - cron: "0 6,18 * * *"  # 6:00 i 18:00 UTC (czyli 8:00 i 20:00 w PL)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 feedgen

      - name: Run script
        run: python trojmiasto_rss.py

      - name: Commit RSS file
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add trojmiasto_rss.xml
          git commit -m "Aktualizacja RSS" || echo "No changes"
          git push
