name: Aktualizuj RSS

permissions:
  contents: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'  # co godzinę

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r trojmiasto_rss.txt

      - name: Uruchom skrypt aktualizacji
        run: python trojmiasto_rss.py

      - name: Commit i push pliku XML
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add trojmiasto_rss.xml
          git commit -m "Dodano wygenerowany plik RSS" || echo "Brak zmian"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git